apiVersion: extensions/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: marta
spec:
  selector:
    matchLabels:
      app: marta
  template:
    metadata:
      labels:
        app: marta
    spec:
      serviceaccountname: marta-chatbot
      containers:
      - image: marta:latest
        name: marta
        env:
          - name: SLACK_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: marta-chatbot-token
                key: SLACK_BOT_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: marta
  labels:
    app: marta
