kind: ClusterRole
 apiVersion: rbac.authorization.k8s.io/v1
 metadata:
   name: pods-list
 rules:
 - apiGroups: [""]
   resources: ["pods"]
   verbs: ["list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: marta-chatbot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pods-list-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: marta-chatbot # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: pods-list # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
